export type Locale = 'hu' | 'en' | 'de'

export const languageOptions: Array<{ value: Locale; flag: string; label: string }> = [
  { value: 'hu', flag: '🇭🇺', label: 'Magyar' },
  { value: 'en', flag: '🇬🇧', label: 'English' },
  { value: 'de', flag: '🇩🇪', label: 'Deutsch' }
]

export const localeTag = (locale: Locale) => locale === 'hu' ? 'hu-HU' : locale === 'de' ? 'de-DE' : 'en-GB'

export function detectLocale(): Locale {
  if (typeof navigator === 'undefined') return 'en'
  const language = navigator.language.toLowerCase()
  if (language.startsWith('hu')) return 'hu'
  if (language.startsWith('de')) return 'de'
  return 'en'
}

const translations = {
  hu: {
    settings: 'Beállítások', todaySoFar: 'Ma eddig', sleepNoun: 'alvás', sleeping: 'ALSZIK', awake: 'ÉBREN',
    fellAsleep: 'Elaludt', wokeUp: 'Felébredt', noPreviousWake: 'Nincs korábbi ébredés', manualEntry: 'Egyedi alvási idő rögzítése',
    todaySleeps: 'Mai alvások', yesterdaySleeps: 'Tegnapi alvások', noSleepToday: 'Még nincs mai alvás.', noSleepYesterday: 'Nem volt tegnap rögzített alvás.', now: 'most',
    history: 'Előzmények', noRecordedSleep: 'Még nincs rögzített alvás.', today: 'Ma', yesterday: 'Tegnap', edit: 'Szerkesztés', delete: 'Törlés',
    statistics: 'Statisztika', day: 'Nap', week: 'Hét', month: 'Hónap', sleepDuration: 'Alvás időtartama', sleep: 'Alvás', overview24h: '24 órás áttekintés', average: 'Átlag', perDay: '/ nap', daytime: 'Nappali', nighttime: 'Éjszakai', insights: 'Insights', wakeWindow: 'Ébrenléti ablak', awakeForNow: 'Ennyi ideje van ébren', typicalWakeWindow: 'Jellemző érték', typicalRange: 'Tipikus tartomány', insightsRange: 'Insights időtartomány', daysShort: 'nap', bySleepOrder: 'Alvássorrend szerint', firstNapWindow: 'Első nappali alvás előtt', secondNapWindow: 'Második nappali alvás előtt', laterNapWindow: 'Későbbi nappali alvás előtt', nightSleepWindow: 'Éjszakai alvás előtt', sampleCountShort: '{count} minta', wakeWindowBasis: '{count} tiszta ébrenléti ablak alapján', wakeWindowCollecting: 'Még gyűjtjük a mintát ({count}/3)', wakeWindowUnavailable: 'Futó alvás közben az aktuális ébrenléti ablak nem számítható.', lowConfidence: 'Korai jelzés', mediumConfidence: 'Stabilabb minta', insightsExcluded: '{count} problémás bejegyzést kihagytunk a számításból.', routinePatterns: 'Rutinminták', observedDays: '{count} megfigyelt nap', routineCollecting: 'Legalább 3 tiszta megfigyelt nap után jelennek meg a rutinminták.', typicalBedtime: 'Jellemző esti elalvás', typicalWakeTime: 'Jellemző reggeli ébredés', typicalNapCount: 'Jellemző nappali alvásszám', routineConsistency: '{consistent}/{count} alkalom ±30 percen belül', napCountRange: 'Tipikus tartomány: {low}–{high}', routineOwnData: 'Kizárólag a saját, tiszta alvásadatok alapján.', similarDays: 'Hasonló napok', closestDays: '3 legközelebbi', similarDaysUnavailable: 'Hasonló napokat csak ébrenléti állapotban, tiszta mai adatokból keresünk.', similarDaysCollecting: 'Még gyűjtjük az összehasonlítható napokat ({count}/3).', similarDayEvidence: '{naps} nappali alvás · {sleep} alvás eddig · {awake} ébren', thenSleptAt: 'Ezután elaludt:', noLaterSleep: 'Nincs későbbi rögzített alvás', similarDaysExplanation: 'Az alvásszám, az addigi összalvás és az ébrenléti idő hasonlósága alapján.', nextSleepEstimate: 'Következő alvás becslése', predictionUnavailable: 'Becslést csak ébrenléti állapotban, tiszta mai adatokból adunk.', predictionCollecting: 'Ehhez az alvássorrendhez még gyűjtjük a mintát ({count}/3).', predictionUpcoming: 'A saját minta alapján közeledik', predictionLikelyNow: 'A saját tipikus tartományban', predictionPassed: 'A saját tipikus tartomány már elmúlt', predictionBasis: '{count} tiszta, azonos alvássorrendű minta alapján ({order}).', predictionDisclaimer: 'Tájékoztató becslés, nem biztos időpont vagy orvosi tanács.', firstNap: 'első nappali alvás', secondNap: 'második nappali alvás', laterNap: 'későbbi nappali alvás', nightSleep: 'éjszakai alvás',
    babyName: 'Baba neve', babyNamePlaceholder: 'Baba neve', language: 'Nyelv', exportData: 'Adatok exportálása', importData: 'Adatok importálása', clearAll: 'Összes alvásadat törlése', localOnly: 'Az adatok jelenleg kizárólag ezen az eszközön maradnak.',
    children: 'Gyerekek', childrenHint: 'Profilok és születési dátumok', addChild: 'Gyerek hozzáadása', editChild: 'Profil szerkesztése', childName: 'Gyerek neve', childNamePlaceholder: 'Pl. Emma', childNameRequired: 'Add meg a gyerek nevét.', birthDate: 'Születési dátum', birthDateMissing: 'Nincs születési dátum', birthDateFuture: 'A születési dátum nem lehet jövőbeli.', birthDateAnalyticsHint: 'Ezt az életkorhoz igazított elemzésekhez használjuk.', optional: 'opcionális', unnamedChild: 'Névtelen profil', chooseChild: 'Gyerek kiválasztása', active: 'Aktív', sleepEntries: '{count} alvás',
    addPhoto: 'Profilkép hozzáadása', changePhoto: 'Profilkép cseréje', removePhoto: 'Eltávolítás', photoLocalHint: 'A profilkép ezen az eszközön marad.', photoInvalid: 'Válassz 12 MB-nál kisebb képfájlt.', photoSaveError: 'A profilképet nem sikerült elmenteni.', positionPhoto: 'Profilkép beállítása', positionPhotoHint: 'Húzd a képet a körben a megfelelő helyre, és nagyíts, ha szükséges.', zoomPhoto: 'Nagyítás', done: 'Kész', saving: 'Mentés…',
    longSleepReminder: '„Még alszik?” jelzés', longSleepReminderHint: '12 óránál hosszabb aktív alvásnál jelez. Soha nem zárja le automatikusan.', startedEarlier: 'Korábban aludt el:', customTime: 'Egyedi idő', stillSleepingQuestion: 'Még alszik?', longSleepReminderText: 'Ez az alvás több mint 12 órája tart. Ellenőrizd, hogy még fut-e.', checkSleepData: 'Ellenőrizd az alvásadatot', invalidTimeWarning: 'Az alvás időpontjai hibásak vagy hiányosak.', futureTimeWarning: 'Az alvás jövőbeli időpontot tartalmaz.', shortDurationWarning: 'Ez az alvás szokatlanul rövid.', staleActiveWarning: 'Egy aktív alvás több mint 12 órája fut.', duplicateWarning: 'Két bejegyzés valószínűleg ugyanazt az alvást rögzíti.', overlapWarning: 'Két alvás időben átfedi egymást.', extremeDurationWarning: 'Szokatlanul hosszú alvást találtam.',
    importFound: 'Az import {children} gyerekprofilt és {count} alvásbejegyzést tartalmaz.', importReplaceQuestion: 'Lecseréljük a jelenlegi adatokat? Előtte automatikusan letöltjük a mostani mentést.', importMigratedV3: 'A V3 mentést biztonságosan V4 formátumra alakítjuk.', importActiveChildReset: 'A hiányzó aktív profilt egy elérhető profilra állítjuk.', importDuplicateChildrenRemoved: '{count} teljesen azonos gyerekprofil-duplikátumot eltávolítunk.', importDuplicateSessionsRemoved: '{count} teljesen azonos alvásduplikátumot eltávolítunk.', importPhotosLocal: '{count} profil helyi képe nincs a JSON mentésben, ezért másik eszközön hiányozhat.', importInvalidChildren: '{count} sérült gyerekprofil található. Az importot adatvesztés nélkül nem lehet folytatni.', importInvalidSessions: '{count} sérült alvásbejegyzés található. Az importot adatvesztés nélkül nem lehet folytatni.', importChildConflict: '{count} azonosítón két eltérő gyerekprofil található.', importSessionConflict: '{count} azonosítón két eltérő alvásbejegyzés található.', importOrphanSessions: '{count} alvásbejegyzés nem létező gyerekprofilra hivatkozik.', importError: 'Importálási hiba.', clearConfirm: 'Biztosan törlöd az összes alvásadatot? Ez nem vonható vissza.', deleteConfirm: 'Biztosan törlöd ezt az alvást?',
    details: 'Részletek', recordSleep: 'Alvás rögzítése', stillSleeping: 'Még alszik', note: 'Megjegyzés', optionalNote: 'Opcionális megjegyzés', save: 'Mentés',
    sleepType: 'Alvás típusa', automatic: 'Automatikus', automaticRule: 'Automatikusan nappali {dayStart}:00–{nightStart}:00 között, azon kívül éjszakai.',
    futureNotAllowed: 'Jövőbeli időpont nem menthető.', wakeAfterSleep: 'A felébredésnek később kell lennie, mint az elalvásnak.', activeExists: 'Már van egy futó alvás.',
    sleeps: 'Alvások', touchSegment: 'Érints meg egy alvási szakaszt a részletekhez', timelineAria: '24 órás alvási idővonal',
    invalidJson: 'A fájl nem érvényes JSON mentés.', invalidBackup: 'Érvénytelen mentés.', wrongBackup: 'Ez nem támogatott Solemi Sleep mentés.', corruptBackup: 'A mentés sérült vagy hiányos alvásadatot tartalmaz.'
  },
  en: {
    settings: 'Settings', todaySoFar: 'Today so far', sleepNoun: 'sleep', sleeping: 'ASLEEP', awake: 'AWAKE',
    fellAsleep: 'Fell asleep', wokeUp: 'Woke up', noPreviousWake: 'No previous wake time', manualEntry: 'Record custom sleep time',
    todaySleeps: "Today's sleep", yesterdaySleeps: "Yesterday's sleep", noSleepToday: 'No sleep recorded today yet.', noSleepYesterday: 'No sleep was recorded yesterday.', now: 'now',
    history: 'History', noRecordedSleep: 'No sleep recorded yet.', today: 'Today', yesterday: 'Yesterday', edit: 'Edit', delete: 'Delete',
    statistics: 'Statistics', day: 'Day', week: 'Week', month: 'Month', sleepDuration: 'Sleep duration', sleep: 'Sleep', overview24h: '24-hour overview', average: 'Average', perDay: '/ day', daytime: 'Daytime', nighttime: 'Nighttime', insights: 'Insights', wakeWindow: 'Wake window', awakeForNow: 'Awake for this long', typicalWakeWindow: 'Typical value', typicalRange: 'Typical range', insightsRange: 'Insights time range', daysShort: 'days', bySleepOrder: 'By sleep order', firstNapWindow: 'Before the first daytime sleep', secondNapWindow: 'Before the second daytime sleep', laterNapWindow: 'Before later daytime sleep', nightSleepWindow: 'Before night sleep', sampleCountShort: '{count} samples', wakeWindowBasis: 'Based on {count} clean wake windows', wakeWindowCollecting: 'Still collecting a pattern ({count}/3)', wakeWindowUnavailable: 'The current wake window is unavailable while sleep is active.', lowConfidence: 'Early signal', mediumConfidence: 'Stronger pattern', insightsExcluded: '{count} problematic entries were excluded from this calculation.', routinePatterns: 'Routine patterns', observedDays: '{count} observed days', routineCollecting: 'Routine patterns appear after at least 3 clean observed days.', typicalBedtime: 'Typical night sleep start', typicalWakeTime: 'Typical morning wake-up', typicalNapCount: 'Typical daytime sleep count', routineConsistency: '{consistent}/{count} within ±30 minutes', napCountRange: 'Typical range: {low}–{high}', routineOwnData: 'Based only on your own clean sleep data.', similarDays: 'Similar days', closestDays: '3 closest', similarDaysUnavailable: 'Similar days are shown only while awake and when today’s data is clean.', similarDaysCollecting: 'Still collecting comparable days ({count}/3).', similarDayEvidence: '{naps} daytime sleeps · {sleep} sleep so far · {awake} awake', thenSleptAt: 'Then fell asleep:', noLaterSleep: 'No later sleep recorded', similarDaysExplanation: 'Matched by daytime sleep count, total sleep so far and current awake time.', nextSleepEstimate: 'Next sleep estimate', predictionUnavailable: 'An estimate is shown only while awake and when today’s data is clean.', predictionCollecting: 'Still collecting this sleep-order pattern ({count}/3).', predictionUpcoming: 'Approaching based on your own pattern', predictionLikelyNow: 'Within your own typical range', predictionPassed: 'Your typical range has already passed', predictionBasis: 'Based on {count} clean samples with the same sleep order ({order}).', predictionDisclaimer: 'An informational estimate, not a guaranteed time or medical advice.', firstNap: 'first daytime sleep', secondNap: 'second daytime sleep', laterNap: 'later daytime sleep', nightSleep: 'night sleep',
    babyName: "Baby's name", babyNamePlaceholder: "Baby's name", language: 'Language', exportData: 'Export data', importData: 'Import data', clearAll: 'Delete all sleep data', localOnly: 'Your data currently stays only on this device.',
    children: 'Children', childrenHint: 'Profiles and birth dates', addChild: 'Add child', editChild: 'Edit profile', childName: "Child's name", childNamePlaceholder: 'e.g. Emma', childNameRequired: "Enter the child's name.", birthDate: 'Birth date', birthDateMissing: 'No birth date', birthDateFuture: 'Birth date cannot be in the future.', birthDateAnalyticsHint: 'This is used for age-aware insights.', optional: 'optional', unnamedChild: 'Unnamed profile', chooseChild: 'Choose child', active: 'Active', sleepEntries: '{count} sleeps',
    addPhoto: 'Add profile photo', changePhoto: 'Change profile photo', removePhoto: 'Remove', photoLocalHint: 'The profile photo stays on this device.', photoInvalid: 'Choose an image smaller than 12 MB.', photoSaveError: 'The profile photo could not be saved.', positionPhoto: 'Position profile photo', positionPhotoHint: 'Drag the photo inside the circle and zoom if needed.', zoomPhoto: 'Zoom', done: 'Done', saving: 'Saving…',
    longSleepReminder: '“Still sleeping?” reminder', longSleepReminderHint: 'Warn after 12 hours of active sleep. It never ends a sleep automatically.', startedEarlier: 'Fell asleep earlier:', customTime: 'Custom time', stillSleepingQuestion: 'Still sleeping?', longSleepReminderText: 'This sleep has been active for more than 12 hours. Check whether it is still running.', checkSleepData: 'Check sleep data', invalidTimeWarning: 'This sleep has invalid or incomplete times.', futureTimeWarning: 'This sleep contains a future time.', shortDurationWarning: 'This sleep is unusually short.', staleActiveWarning: 'An active sleep has been running for more than 12 hours.', duplicateWarning: 'Two entries probably describe the same sleep.', overlapWarning: 'Two sleep entries overlap in time.', extremeDurationWarning: 'An unusually long sleep was found.',
    importFound: 'The import contains {children} child profiles and {count} sleep entries.', importReplaceQuestion: 'Replace the current data? The current backup will be downloaded first.', importMigratedV3: 'The V3 backup will be safely migrated to V4.', importActiveChildReset: 'The missing active profile will be reset to an available profile.', importDuplicateChildrenRemoved: '{count} fully identical duplicate child profiles will be removed.', importDuplicateSessionsRemoved: '{count} fully identical duplicate sleep entries will be removed.', importPhotosLocal: 'Local photos for {count} profiles are not included in JSON and may be missing on another device.', importInvalidChildren: '{count} damaged child profiles were found. Import cannot continue without data loss.', importInvalidSessions: '{count} damaged sleep entries were found. Import cannot continue without data loss.', importChildConflict: '{count} child IDs contain conflicting profiles.', importSessionConflict: '{count} sleep IDs contain conflicting entries.', importOrphanSessions: '{count} sleep entries refer to a missing child profile.', importError: 'Import error.', clearConfirm: 'Delete all sleep data? This cannot be undone.', deleteConfirm: 'Delete this sleep entry?',
    details: 'Details', recordSleep: 'Record sleep', stillSleeping: 'Still sleeping', note: 'Note', optionalNote: 'Optional note', save: 'Save',
    sleepType: 'Sleep type', automatic: 'Automatic', automaticRule: 'Automatically daytime from {dayStart}:00–{nightStart}:00, nighttime otherwise.',
    futureNotAllowed: 'A future time cannot be saved.', wakeAfterSleep: 'Wake time must be later than sleep time.', activeExists: 'There is already an active sleep.',
    sleeps: 'Sleep', touchSegment: 'Tap a sleep segment for details', timelineAria: '24-hour sleep timeline',
    invalidJson: 'The file is not a valid JSON backup.', invalidBackup: 'Invalid backup.', wrongBackup: 'This is not a supported Solemi Sleep backup.', corruptBackup: 'The backup contains damaged or incomplete sleep data.'
  },
  de: {
    settings: 'Einstellungen', todaySoFar: 'Heute bisher', sleepNoun: 'Schlaf', sleeping: 'SCHLÄFT', awake: 'WACH',
    fellAsleep: 'Eingeschlafen', wokeUp: 'Aufgewacht', noPreviousWake: 'Keine frühere Aufwachzeit', manualEntry: 'Eigene Schlafzeit eintragen',
    todaySleeps: 'Heutiger Schlaf', yesterdaySleeps: 'Gestriger Schlaf', noSleepToday: 'Heute wurde noch kein Schlaf erfasst.', noSleepYesterday: 'Gestern wurde kein Schlaf erfasst.', now: 'jetzt',
    history: 'Verlauf', noRecordedSleep: 'Noch kein Schlaf erfasst.', today: 'Heute', yesterday: 'Gestern', edit: 'Bearbeiten', delete: 'Löschen',
    statistics: 'Statistik', day: 'Tag', week: 'Woche', month: 'Monat', sleepDuration: 'Schlafdauer', sleep: 'Schlaf', overview24h: '24-Stunden-Übersicht', average: 'Durchschnitt', perDay: '/ Tag', daytime: 'Tagsüber', nighttime: 'Nachts', insights: 'Insights', wakeWindow: 'Wachfenster', awakeForNow: 'So lange bereits wach', typicalWakeWindow: 'Typischer Wert', typicalRange: 'Typischer Bereich', insightsRange: 'Insights-Zeitraum', daysShort: 'Tage', bySleepOrder: 'Nach Schlafreihenfolge', firstNapWindow: 'Vor dem ersten Tagschlaf', secondNapWindow: 'Vor dem zweiten Tagschlaf', laterNapWindow: 'Vor späterem Tagschlaf', nightSleepWindow: 'Vor dem Nachtschlaf', sampleCountShort: '{count} Werte', wakeWindowBasis: 'Basierend auf {count} sauberen Wachfenstern', wakeWindowCollecting: 'Muster wird noch gesammelt ({count}/3)', wakeWindowUnavailable: 'Während eines laufenden Schlafs ist das aktuelle Wachfenster nicht verfügbar.', lowConfidence: 'Frühes Signal', mediumConfidence: 'Stabileres Muster', insightsExcluded: '{count} problematische Einträge wurden aus der Berechnung ausgeschlossen.', routinePatterns: 'Routinemuster', observedDays: '{count} beobachtete Tage', routineCollecting: 'Routinemuster erscheinen nach mindestens 3 sauberen beobachteten Tagen.', typicalBedtime: 'Typischer Beginn des Nachtschlafs', typicalWakeTime: 'Typisches morgendliches Aufwachen', typicalNapCount: 'Typische Anzahl Tagschläfchen', routineConsistency: '{consistent}/{count} innerhalb von ±30 Minuten', napCountRange: 'Typischer Bereich: {low}–{high}', routineOwnData: 'Nur auf Basis deiner eigenen sauberen Schlafdaten.', similarDays: 'Ähnliche Tage', closestDays: '3 ähnlichste', similarDaysUnavailable: 'Ähnliche Tage werden nur im Wachzustand und bei sauberen heutigen Daten angezeigt.', similarDaysCollecting: 'Vergleichbare Tage werden noch gesammelt ({count}/3).', similarDayEvidence: '{naps} Tagschläfchen · {sleep} Schlaf bisher · {awake} wach', thenSleptAt: 'Danach eingeschlafen:', noLaterSleep: 'Kein späterer Schlaf erfasst', similarDaysExplanation: 'Abgleich nach Anzahl der Tagschläfchen, bisherigem Gesamtschlaf und aktueller Wachzeit.', nextSleepEstimate: 'Nächsten Schlaf schätzen', predictionUnavailable: 'Eine Schätzung erscheint nur im Wachzustand und bei sauberen heutigen Daten.', predictionCollecting: 'Dieses Schlafreihenfolge-Muster wird noch gesammelt ({count}/3).', predictionUpcoming: 'Nähert sich nach deinem eigenen Muster', predictionLikelyNow: 'In deinem eigenen typischen Bereich', predictionPassed: 'Dein typischer Bereich ist bereits vorbei', predictionBasis: 'Basierend auf {count} sauberen Werten derselben Schlafreihenfolge ({order}).', predictionDisclaimer: 'Informative Schätzung, keine sichere Uhrzeit oder medizinische Beratung.', firstNap: 'erster Tagschlaf', secondNap: 'zweiter Tagschlaf', laterNap: 'späterer Tagschlaf', nightSleep: 'Nachtschlaf',
    babyName: 'Name des Babys', babyNamePlaceholder: 'Name des Babys', language: 'Sprache', exportData: 'Daten exportieren', importData: 'Daten importieren', clearAll: 'Alle Schlafdaten löschen', localOnly: 'Deine Daten bleiben derzeit ausschließlich auf diesem Gerät.',
    children: 'Kinder', childrenHint: 'Profile und Geburtsdaten', addChild: 'Kind hinzufügen', editChild: 'Profil bearbeiten', childName: 'Name des Kindes', childNamePlaceholder: 'z. B. Emma', childNameRequired: 'Gib den Namen des Kindes ein.', birthDate: 'Geburtsdatum', birthDateMissing: 'Kein Geburtsdatum', birthDateFuture: 'Das Geburtsdatum darf nicht in der Zukunft liegen.', birthDateAnalyticsHint: 'Dies wird für altersbezogene Einblicke verwendet.', optional: 'optional', unnamedChild: 'Unbenanntes Profil', chooseChild: 'Kind auswählen', active: 'Aktiv', sleepEntries: '{count} Schlafphasen',
    addPhoto: 'Profilbild hinzufügen', changePhoto: 'Profilbild ändern', removePhoto: 'Entfernen', photoLocalHint: 'Das Profilbild bleibt auf diesem Gerät.', photoInvalid: 'Wähle ein Bild unter 12 MB.', photoSaveError: 'Das Profilbild konnte nicht gespeichert werden.', positionPhoto: 'Profilbild ausrichten', positionPhotoHint: 'Ziehe das Bild im Kreis an die gewünschte Position und vergrößere es bei Bedarf.', zoomPhoto: 'Vergrößerung', done: 'Fertig', saving: 'Speichern…',
    longSleepReminder: '„Schläft noch?“-Hinweis', longSleepReminderHint: 'Warnt nach 12 Stunden aktivem Schlaf. Der Schlaf wird nie automatisch beendet.', startedEarlier: 'Früher eingeschlafen:', customTime: 'Eigene Zeit', stillSleepingQuestion: 'Schläft noch?', longSleepReminderText: 'Dieser Schlaf läuft seit mehr als 12 Stunden. Prüfe, ob er noch aktiv ist.', checkSleepData: 'Schlafdaten prüfen', invalidTimeWarning: 'Dieser Schlaf hat ungültige oder unvollständige Zeiten.', futureTimeWarning: 'Dieser Schlaf enthält eine zukünftige Zeit.', shortDurationWarning: 'Dieser Schlaf ist ungewöhnlich kurz.', staleActiveWarning: 'Ein aktiver Schlaf läuft seit mehr als 12 Stunden.', duplicateWarning: 'Zwei Einträge beschreiben wahrscheinlich denselben Schlaf.', overlapWarning: 'Zwei Schlafeinträge überschneiden sich zeitlich.', extremeDurationWarning: 'Ein ungewöhnlich langer Schlaf wurde gefunden.',
    importFound: 'Der Import enthält {children} Kinderprofile und {count} Schlafeinträge.', importReplaceQuestion: 'Aktuelle Daten ersetzen? Zuerst wird automatisch die aktuelle Sicherung heruntergeladen.', importMigratedV3: 'Das V3-Backup wird sicher auf V4 migriert.', importActiveChildReset: 'Das fehlende aktive Profil wird auf ein verfügbares Profil gesetzt.', importDuplicateChildrenRemoved: '{count} vollständig identische doppelte Kinderprofile werden entfernt.', importDuplicateSessionsRemoved: '{count} vollständig identische doppelte Schlafeinträge werden entfernt.', importPhotosLocal: 'Lokale Fotos für {count} Profile sind nicht im JSON enthalten und können auf einem anderen Gerät fehlen.', importInvalidChildren: '{count} beschädigte Kinderprofile gefunden. Der Import kann ohne Datenverlust nicht fortgesetzt werden.', importInvalidSessions: '{count} beschädigte Schlafeinträge gefunden. Der Import kann ohne Datenverlust nicht fortgesetzt werden.', importChildConflict: '{count} Kinder-IDs enthalten widersprüchliche Profile.', importSessionConflict: '{count} Schlaf-IDs enthalten widersprüchliche Einträge.', importOrphanSessions: '{count} Schlafeinträge verweisen auf ein fehlendes Kinderprofil.', importError: 'Importfehler.', clearConfirm: 'Alle Schlafdaten löschen? Dies kann nicht rückgängig gemacht werden.', deleteConfirm: 'Diesen Schlafeintrag löschen?',
    details: 'Details', recordSleep: 'Schlaf eintragen', stillSleeping: 'Schläft noch', note: 'Notiz', optionalNote: 'Optionale Notiz', save: 'Speichern',
    sleepType: 'Schlaftyp', automatic: 'Automatisch', automaticRule: 'Automatisch tagsüber von {dayStart}:00–{nightStart}:00, sonst nachts.',
    futureNotAllowed: 'Eine zukünftige Uhrzeit kann nicht gespeichert werden.', wakeAfterSleep: 'Die Aufwachzeit muss nach der Einschlafzeit liegen.', activeExists: 'Es gibt bereits einen laufenden Schlaf.',
    sleeps: 'Schlaf', touchSegment: 'Tippe auf einen Schlafabschnitt für Details', timelineAria: '24-Stunden-Schlafzeitleiste',
    invalidJson: 'Die Datei ist kein gültiges JSON-Backup.', invalidBackup: 'Ungültiges Backup.', wrongBackup: 'Dies ist kein unterstütztes Solemi Sleep Backup.', corruptBackup: 'Das Backup enthält beschädigte oder unvollständige Schlafdaten.'
  }
} as const

export type TranslationKey = keyof typeof translations.en

export function t(locale: Locale, key: TranslationKey, values?: Record<string, string | number>) {
  let text: string = translations[locale][key]
  if (values) Object.entries(values).forEach(([name, value]) => { text = text.replace(`{${name}}`, String(value)) })
  return text
}
